require("manuel.plugins-setup")
require("manuel.core.options")
require("manuel.core.keymaps")
require("manuel.core.colorscheme")
require("manuel.plugins.comment")
require("manuel.plugins.nvim-tree")
require("manuel.plugins.lualine")
require("manuel.plugins.telescope")
